version: "3.8"

services:
  db:
    container_name: Nimbus-DB
    image: "postgres:13"
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: Nimbus
    volumes:
      - db:/data/db
    networks:
      - network-data

  spring-app:
    container_name: Nimbus
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://Nimbus-DB:5432/Nimbus
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SWAGGER_ACTIVATION=false
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_APPLICATION_NAME=Nimbus
      - SPRING_SESSION_STORE_TYPE=jdbc
      - SERVER_PORT=8085
      - SPRING_SESSION_JDBC_INITIALIZE_SCHEMA=always
    networks:
      - network-data
    depends_on:
      - db

  jenkins:
    container_name: Nimbus-Jenkins
    image: "jenkins/jenkins:lts"
    restart: always
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network-data
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

networks:
  network-data:
    driver: bridge

volumes:
  db:
    driver: local
  jenkins_home:
    driver: local
