server:
  port: 8084

spring:
  application:
    name: "Nimbus"
  datasource:
      url: "jdbc:postgresql://Nimbus-DB:5432/Nimbus"
      username: "admin"
      password: "admin"
      driver-class-name: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: "update"
  profiles:
    active: "prod"